version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/web"
      - "./docker/nginx/histologie.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php

  php:
    build: './docker/php'
    links:
      - mysql
    volumes:
      - "./:/web"


  mysql:
    container_name: ${MYSQL_HOSTNAME}
    hostname: ${MYSQL_HOSTNAME}
    build: './docker/mysql'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./:/web"
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_HOSTNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
